# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.3.1"

VMName = "vm-spw"

Vagrant.configure("2") do |config|
  ###########################################################
  #
  # VM
  #
  #  @see Boxes at https://vagrantcloud.com/search.
  #
  config.vm.provider "hyperv"
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = VMName

  ###########################################################
  #
  # Disks
  #
  #  @see https://www.vagrantup.com/docs/disks/configuration
  #  @see https://www.vagrantup.com/docs/disks/hyperv/usage
  #
  config.vm.disk :disk, primary: true, size: "40GB", Fixed: true

  ###########################################################
  #
  # Network
  #
  config.vm.network "public_network", bridge: "Default Switch"

  ###########################################################
  #
  # hyperv specific
  #
  #  @see https://www.vagrantup.com/docs/providers/hyperv/configuration
  #
  config.vm.provider "hyperv" do |h|
    h.auto_start_action = "Nothing"
    h.cpus = 2
    h.memory = 2000
    h.maxmemory = 6000
	h.enable_checkpoints = false
    h.vmname = config.vm.hostname
  end

  ###########################################################
  #
  # Provisionner
  #
  #    vagrant provision --provision-with sshkey
  #
  #  @see https://developer.hashicorp.com/vagrant/docs/provisioning/basic_usage
  #

  config.vm.provision "install", type: "shell", inline: <<-SHELL
    set -o errexit
    export DEBIAN_FRONTEND=noninteractive
    
    echo "**************** Install google chrome *************"
	wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
	sh -c 'echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
	apt-get update
	apt-get install -y google-chrome-stable
	
  SHELL
end
